name: "IREC 2021 Config"

# DEBUG decides to print information
DEBUG: true

# File where simulation data is located
sim_file: "other/data/sim_irec2019.json"

# Delay after apogee before deploying 1st parachute
apogee_delay: 0.0

# Delay after main before deploying 2nd parachute
main_delay: 0.0

# Altitude at which to deploy 2nd parachute
main_altitude: 381  # 381 m is 1250 feet

# ID of base station Xbee to communicate with
remote_xbee_id: "0013A2004195721E"

# FIDI
FIDI: false

# Plugins start certain functions at different times
plugins:
  halt_start:
    - "SenseHatData"
    - "USBGPS"
    - "XbeeComm"
    - "FileLogging"
  apogee_start:
    - "USBRelay1"
  eject_start:
    - "USBRelay2"
